# Generated by Django 2.2.5 on 2019-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('email', models.CharField(max_length=50, verbose_name='Addresse mail')),
                ('numerofact', models.PositiveSmallIntegerField(unique=True, verbose_name='Numéro de Facture')),
                ('date_debut', models.DateField(verbose_name='date début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
            ],
        ),
    ]
