# Generated by Django 2.2.5 on 2019-09-24 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=250)),
                ('nom_contact_client', models.CharField(blank=True, max_length=250)),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('code_postal', models.CharField(blank=True, max_length=5)),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('rib_iban', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=16)),
                ('TVA', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('calc_tva_seule', models.CharField(blank=True, max_length=16)),
                ('calc_tva_appli', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('codenaf', models.CharField(blank=True, max_length=8)),
                ('mention_legale', models.TextField(blank=True)),
                ('rib', models.CharField(blank=True, max_length=100)),
                ('entete', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_fact', models.DateField(default=django.utils.timezone.now)),
                ('type_facture', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_echeance', models.DateField()),
                ('intitule', models.CharField(max_length=250)),
                ('date_prestation', models.DateField()),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('prix_HT', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('prix_TTC', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.Client')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.Prestataire')),
            ],
        ),
    ]
