# Generated by Django 2.2.5 on 2019-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('Annuelle', 'annuelle'), ('Mensuelle', 'mensuelle'), ('Ponctuelle', 'ponctuelle')], default='Ponctuelle', max_length=10, verbose_name='Type facture'),
        ),
    ]
