# Generated by Django 2.1.7 on 2019-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_auto_20191010_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='descriptif',
        ),
        migrations.AddField(
            model_name='facture',
            name='nombre_echeance',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facture',
            name='prestation',
            field=models.ManyToManyField(to='facture.Prestation'),
        ),
    ]
