# Generated by Django 2.1.7 on 2019-11-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_auto_20191124_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestToFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, verbose_name='quant')),
                ('prix_unitaire_HT', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='facture.Facture')),
            ],
        ),
        migrations.RemoveField(
            model_name='prestation',
            name='detail',
        ),
        migrations.AddField(
            model_name='prestation',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='intitule',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='presttofact',
            name='prest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_prestations', to='facture.Prestation'),
        ),
    ]
