# Generated by Django 2.1.7 on 2019-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_auto_20191124_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prix_HT',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prix_TTC',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prix_unitaire',
        ),
    ]
